---
os: linux
dist: bionic
language: c

jobs:
    include:
        - arch: armhf
        - arch: amd64

install:
    - sudo apt-get -y install libogg-dev libasound-dev dpkg-dev fakeroot debhelper
    - sudo apt-get -y install libsdl-image1.2-dev libsdl-ttf2.0-dev libsdl-gfx1.2-dev portaudio19-dev libflac-dev libmad0-dev

# The output of the tolua++ program has been committed to version control,
# so try and force using it (the tolua++ program is not installed in the build
# environment)
before_script:
    - touch src/squeezeplay/src/ui/lua_jiveui.c

script:
    - cd src && make -f Makefile.linux
    - make -C squeezeplay squeezeplay-deb

deploy:
    provider: releases
    token: "$GITHUB_TOKEN"
    skip_cleanup: true
    prerelease: true
    overwrite: true
    on:
        tags: true
    file_glob: true
    file:
        - "../build/*.tgz"
        - "*.deb"
